services:
  db:
    image: postgres:15
    container_name: telor-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telor-network

  telor-api:
    image: hendika/telor-api:latest
    container_name: telor-api
    restart: always
    ports:
      - "3636:3636"
    env_file:
      - .env
    networks:
      - telor-network

volumes:
  postgres_data:

networks:
  telor-network:
    external: true
